/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package horario.gui;

import horario.dto.Hora;
import horario.logica.LogicaNegocio;
import java.awt.Component;
import java.awt.Image;
import java.io.File;
import java.util.Enumeration;
import javax.imageio.ImageIO;
import javax.swing.AbstractButton;
import javax.swing.JCheckBox;

/**
 *
 * @author Eduardo
 */
public class VentanaAlta extends javax.swing.JDialog {

    private VentanaPrincipal padre;

    /**
     * Creates new form VentanaAlta
     */
    public VentanaAlta(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        padre = (VentanaPrincipal) parent;
        //ponemos un icono a la ventana alta
        try {
            File imagen = new File("src/horario/gui/img/icono.png");
            Image image = ImageIO.read(imagen);
            this.setIconImage(image);
        } catch (Throwable e) {
            e.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bGDia = new javax.swing.ButtonGroup();
        jPanelDia = new javax.swing.JPanel();
        jRBLunes = new javax.swing.JRadioButton();
        jRBMartes = new javax.swing.JRadioButton();
        jRBMiercoles = new javax.swing.JRadioButton();
        jRBJueves = new javax.swing.JRadioButton();
        jRBViernes = new javax.swing.JRadioButton();
        jPanelHora = new javax.swing.JPanel();
        jCBHora1 = new javax.swing.JCheckBox();
        jCBHora2 = new javax.swing.JCheckBox();
        jCBHora3 = new javax.swing.JCheckBox();
        jCBHora4 = new javax.swing.JCheckBox();
        jCBHora5 = new javax.swing.JCheckBox();
        jCBHora6 = new javax.swing.JCheckBox();
        jLabel1 = new javax.swing.JLabel();
        jTFModulo = new javax.swing.JTextField();
        jBAnadir = new javax.swing.JButton();
        jLError = new javax.swing.JLabel();
        jLAviso = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanelDia.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Día", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 18), new java.awt.Color(0, 0, 255))); // NOI18N

        bGDia.add(jRBLunes);
        jRBLunes.setSelected(true);
        jRBLunes.setText("Lunes");
        jRBLunes.setActionCommand("1");
        jRBLunes.setName("1"); // NOI18N
        jRBLunes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                quitarmensajes(evt);
            }
        });

        bGDia.add(jRBMartes);
        jRBMartes.setText("Martes");
        jRBMartes.setActionCommand("2");
        jRBMartes.setName("2"); // NOI18N
        jRBMartes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                quitarmensajes(evt);
            }
        });

        bGDia.add(jRBMiercoles);
        jRBMiercoles.setText("Miércoles");
        jRBMiercoles.setActionCommand("3");
        jRBMiercoles.setName("3"); // NOI18N
        jRBMiercoles.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                quitarmensajes(evt);
            }
        });

        bGDia.add(jRBJueves);
        jRBJueves.setText("Jueves");
        jRBJueves.setActionCommand("4");
        jRBJueves.setName("4"); // NOI18N
        jRBJueves.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                quitarmensajes(evt);
            }
        });

        bGDia.add(jRBViernes);
        jRBViernes.setText("Viernes");
        jRBViernes.setActionCommand("5");
        jRBViernes.setName("5"); // NOI18N
        jRBViernes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                quitarmensajes(evt);
            }
        });

        javax.swing.GroupLayout jPanelDiaLayout = new javax.swing.GroupLayout(jPanelDia);
        jPanelDia.setLayout(jPanelDiaLayout);
        jPanelDiaLayout.setHorizontalGroup(
            jPanelDiaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDiaLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jRBLunes)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jRBMartes)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRBMiercoles)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jRBJueves)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRBViernes)
                .addContainerGap(22, Short.MAX_VALUE))
        );
        jPanelDiaLayout.setVerticalGroup(
            jPanelDiaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDiaLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanelDiaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRBLunes)
                    .addComponent(jRBMartes)
                    .addComponent(jRBMiercoles)
                    .addComponent(jRBJueves)
                    .addComponent(jRBViernes))
                .addContainerGap(31, Short.MAX_VALUE))
        );

        jPanelHora.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Hora", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 18), new java.awt.Color(0, 0, 255))); // NOI18N

        jCBHora1.setText("8:25 9:20");
        jCBHora1.setActionCommand("1");
        jCBHora1.setName("1"); // NOI18N
        jCBHora1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                quitarmensajes(evt);
            }
        });

        jCBHora2.setText("9:20 10:15");
        jCBHora2.setActionCommand("2");
        jCBHora2.setName("2"); // NOI18N
        jCBHora2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                quitarmensajes(evt);
            }
        });

        jCBHora3.setText("10:15 11:10");
        jCBHora3.setActionCommand("3");
        jCBHora3.setName("3"); // NOI18N
        jCBHora3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                quitarmensajes(evt);
            }
        });

        jCBHora4.setText("11:40 12:35");
        jCBHora4.setActionCommand("4");
        jCBHora4.setName("4"); // NOI18N
        jCBHora4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                quitarmensajes(evt);
            }
        });

        jCBHora5.setText("12:35 13:30");
        jCBHora5.setActionCommand("5");
        jCBHora5.setName("5"); // NOI18N
        jCBHora5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                quitarmensajes(evt);
            }
        });

        jCBHora6.setText("13:30 14:25");
        jCBHora6.setActionCommand("6");
        jCBHora6.setName("6"); // NOI18N
        jCBHora6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                quitarmensajes(evt);
            }
        });

        javax.swing.GroupLayout jPanelHoraLayout = new javax.swing.GroupLayout(jPanelHora);
        jPanelHora.setLayout(jPanelHoraLayout);
        jPanelHoraLayout.setHorizontalGroup(
            jPanelHoraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelHoraLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelHoraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jCBHora1)
                    .addComponent(jCBHora4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanelHoraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanelHoraLayout.createSequentialGroup()
                        .addComponent(jCBHora2)
                        .addGap(42, 42, 42)
                        .addComponent(jCBHora3))
                    .addGroup(jPanelHoraLayout.createSequentialGroup()
                        .addComponent(jCBHora5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jCBHora6)))
                .addGap(17, 17, 17))
        );
        jPanelHoraLayout.setVerticalGroup(
            jPanelHoraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelHoraLayout.createSequentialGroup()
                .addGroup(jPanelHoraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCBHora1)
                    .addComponent(jCBHora2)
                    .addComponent(jCBHora3))
                .addGap(18, 18, 18)
                .addGroup(jPanelHoraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCBHora4)
                    .addComponent(jCBHora5)
                    .addComponent(jCBHora6))
                .addGap(0, 17, Short.MAX_VALUE))
        );

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText("Módulo:");

        jTFModulo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                quitarmensajes(evt);
            }
        });

        jBAnadir.setText("Añadir");
        jBAnadir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBAnadirActionPerformed(evt);
            }
        });

        jLError.setForeground(new java.awt.Color(255, 0, 0));
        jLError.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jLAviso.setForeground(new java.awt.Color(51, 51, 255));
        jLAviso.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanelHora, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanelDia, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTFModulo, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLError, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLAviso, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(142, 142, 142)
                        .addComponent(jBAnadir, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLAviso, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelDia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelHora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTFModulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLError, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBAnadir)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBAnadirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBAnadirActionPerformed
        String dia = "";
        String hora = "";
        //confirmación de que se metio un módulo
        if (jTFModulo.getText().equals("")) {
            jLError.setText("Debes de introducir un módulo");
        } else {
            //recorre todos los radioButton del grupo gBDia
            for (Enumeration<AbstractButton> buttons = bGDia.getElements(); buttons.hasMoreElements();) {
                AbstractButton button = buttons.nextElement();

                if (button.isSelected()) {
                    dia = button.getActionCommand();
                    break;
                }
            }

            Boolean selec = false;
            //recorre todos los checkBox del grupo gBHora
            for (Component cb : jPanelHora.getComponents()) {
                if (((JCheckBox) cb).isSelected()) { //si está seleccionado
                    selec = true;
                    hora = ((JCheckBox) cb).getActionCommand();
                    Hora ohora = new Hora(dia, hora, jTFModulo.getText());
                    LogicaNegocio.anadirHora(ohora);
                    ((JCheckBox) cb).setSelected(false); //lo deselecciono
                }
            }
            if (selec == false) {
                jLError.setText("Debes de seleccionar una hora"); //no hay seleccionada una hora
            } else {
                mostrarMensaje();
                padre.refrescarHorario();

            }
        }

    }//GEN-LAST:event_jBAnadirActionPerformed

    private void quitarmensajes(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_quitarmensajes
        jLAviso.setText("");
        jLError.setText("");
    }//GEN-LAST:event_quitarmensajes

    private void mostrarMensaje() {
        jLAviso.setText("Alta Correcta");
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaAlta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaAlta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaAlta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaAlta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                VentanaAlta dialog = new VentanaAlta(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup bGDia;
    private javax.swing.JButton jBAnadir;
    private javax.swing.JCheckBox jCBHora1;
    private javax.swing.JCheckBox jCBHora2;
    private javax.swing.JCheckBox jCBHora3;
    private javax.swing.JCheckBox jCBHora4;
    private javax.swing.JCheckBox jCBHora5;
    private javax.swing.JCheckBox jCBHora6;
    private javax.swing.JLabel jLAviso;
    private javax.swing.JLabel jLError;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanelDia;
    private javax.swing.JPanel jPanelHora;
    private javax.swing.JRadioButton jRBJueves;
    private javax.swing.JRadioButton jRBLunes;
    private javax.swing.JRadioButton jRBMartes;
    private javax.swing.JRadioButton jRBMiercoles;
    private javax.swing.JRadioButton jRBViernes;
    private javax.swing.JTextField jTFModulo;
    // End of variables declaration//GEN-END:variables
}
